# Generated by Django 5.1.4 on 2025-01-03 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('assigned', 'Assignée'), ('in_progress', 'En cours'), ('completed', 'Terminée')], max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('deliverer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.delivererprofile')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
        ),
    ]
